project_name: go-helloworld
builds:
  - 
    binary: go-helloworld
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - 386

    #hooks:
    #    post: ./distribution/npm/npm-release.sh
 
archive:
  format: tar.gz

# Publish to Github Releases 
release:
    github:
        owner: sanathkr
        name: go-helloworld
 
